// dungeon-corpses.js
// Dead adventurer / skeleton templates (corpse interactables).
// Pure data — no dependencies on other modules.

var DUNGEON_CORPSES = [
  // Adventurer types — better loot
  {
    id: 'fallen_adventurer',
    name: 'Fallen Adventurer',
    description: 'A fallen adventurer, their pack still intact.',
    goldMin: 5, goldMax: 30,
    resources: ['iron_ore', 'herbs', 'potion_health'],
    resourceChance: 0.60,
    cardChance: 0.03,
    bookChanceMult: 1.0,
    themeAffinity: null,
  },
  {
    id: 'dead_scholar',
    name: 'Dead Scholar',
    description: 'A scholar\'s remains, clutching a leather journal.',
    goldMin: 2, goldMax: 15,
    resources: ['herbs', 'glass_vial', 'mana_crystal'],
    resourceChance: 0.40,
    cardChance: 0.02,
    bookChanceMult: 2.0,
    themeAffinity: ['ancient_library', 'overgrown_temple', 'throne_dungeon'],
  },
  {
    id: 'slain_knight',
    name: 'Slain Knight',
    description: 'A knight in battered armor, sword still in hand.',
    goldMin: 10, goldMax: 40,
    resources: ['iron_bar', 'bronze_bar', 'potion_health'],
    resourceChance: 0.55,
    cardChance: 0.04,
    bookChanceMult: 0.8,
    themeAffinity: ['stone_keep', 'grand_hall', 'armory_vault', 'catacombs'],
  },
  {
    id: 'dead_mage',
    name: 'Dead Mage',
    description: 'A mage\'s robes, singed. Arcane residue lingers.',
    goldMin: 3, goldMax: 20,
    resources: ['mana_crystal', 'glass_lens', 'herbs'],
    resourceChance: 0.50,
    cardChance: 0.05,
    bookChanceMult: 1.5,
    themeAffinity: ['crystal_cavern', 'shadow_realm', 'floating_islands'],
  },
  {
    id: 'merchant_remains',
    name: 'Merchant Remains',
    description: 'A merchant\'s skeleton surrounded by scattered goods.',
    goldMin: 15, goldMax: 50,
    resources: ['gem_rough', 'glass', 'cogs', 'springs'],
    resourceChance: 0.70,
    cardChance: 0.02,
    bookChanceMult: 0.5,
    themeAffinity: null,
  },
  // Skeleton types — less loot, more atmospheric/lore-focused
  {
    id: 'ancient_skeleton',
    name: 'Ancient Skeleton',
    description: 'Bones centuries old, still wearing rusted armor.',
    goldMin: 1, goldMax: 10,
    resources: ['iron_ore', 'stone'],
    resourceChance: 0.30,
    cardChance: 0.01,
    bookChanceMult: 1.0,
    themeAffinity: ['catacombs', 'bone_yard', 'sand_tomb'],
  },
  {
    id: 'skeleton_party',
    name: 'Skeleton Party',
    description: 'Three skeletons slumped against each other. They didn\'t make it.',
    goldMin: 5, goldMax: 25,
    resources: ['iron_ore', 'herbs', 'potion_health'],
    resourceChance: 0.45,
    cardChance: 0.03,
    bookChanceMult: 1.0,
    themeAffinity: null,
  },
  {
    id: 'chained_skeleton',
    name: 'Chained Skeleton',
    description: 'A skeleton chained to the wall. A prisoner, long forgotten.',
    goldMin: 0, goldMax: 5,
    resources: ['iron_ore'],
    resourceChance: 0.20,
    cardChance: 0.01,
    bookChanceMult: 1.2,
    themeAffinity: ['stone_keep', 'grand_hall', 'throne_dungeon'],
  },
  {
    id: 'robed_skeleton',
    name: 'Robed Skeleton',
    description: 'A skeleton in tattered robes, a faded tome nearby.',
    goldMin: 1, goldMax: 8,
    resources: ['herbs', 'mana_crystal'],
    resourceChance: 0.35,
    cardChance: 0.02,
    bookChanceMult: 2.0,
    themeAffinity: ['overgrown_temple', 'ancient_library', 'shadow_realm'],
  },
  {
    id: 'skeleton_at_desk',
    name: 'Skeleton at Desk',
    description: 'A skeleton seated at a crumbling desk, quill in hand.',
    goldMin: 2, goldMax: 12,
    resources: ['glass_vial', 'herbs'],
    resourceChance: 0.30,
    cardChance: 0.01,
    bookChanceMult: 2.0,
    themeAffinity: ['ancient_library', 'clockwork_maze', 'throne_dungeon'],
  },
  {
    id: 'crushed_remains',
    name: 'Crushed Remains',
    description: 'Remains beneath a collapsed ceiling beam.',
    goldMin: 0, goldMax: 8,
    resources: ['stone', 'iron_ore'],
    resourceChance: 0.25,
    cardChance: 0.01,
    bookChanceMult: 0.5,
    themeAffinity: ['crystal_cavern', 'lava_rift', 'frozen_depths'],
  },
  {
    id: 'ritual_corpse',
    name: 'Ritual Corpse',
    description: 'A body arranged in a ritual circle. Dark stains surround it.',
    goldMin: 3, goldMax: 18,
    resources: ['mana_crystal', 'gem_rough', 'herbs'],
    resourceChance: 0.50,
    cardChance: 0.04,
    bookChanceMult: 1.8,
    themeAffinity: ['shadow_realm', 'bone_yard', 'catacombs', 'blood_altar'],
  },
];

module.exports = { DUNGEON_CORPSES };
